Document: packaage
Title: Debian packaage Manual
Author: <insert document author here>
Abstract: This manual describes what packaage is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/packaage/packaage.sgml.gz

Format: postscript
Files: /usr/share/doc/packaage/packaage.ps.gz

Format: text
Files: /usr/share/doc/packaage/packaage.text.gz

Format: HTML
Index: /usr/share/doc/packaage/html/index.html
Files: /usr/share/doc/packaage/html/*.html
